query GetTeamMembers($team: String!, $org: String!) {
  organization(login: $org) {
    team(slug: $team) {
      members {
        edges {
          node {
            login
          }
        }
      }
    }
  }
}
